[新機能]: 直剣スキル「スラスト」の実装
eryuLab/SkillMaster pull request #172
Opened 2022-10-17 09:40 UTC by Koryu25

### 具体的な実装方法または変更点
レイザースタブのgetTarget()を使い、正面に突撃するスキルを作成しました

### 補足事項
N/A

### 関連するIssue
- close #157

2022-10-17 13:02 UTC, hirotask requested changes
レビュー終わりました。
何点か修正してほしい点があるので、修正お願いします。

2022-10-17 13:02 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
> +                entity.velocity = vector
[ここ](https://note.com/cyberz_cto/n/n26f535d6c575#HPZ6C)にある通り、このコードは論理的凝集と呼ばれる**よくないパターン**です。機能追加や変更があった際に、条件が増えたり複雑になる可能性があります。
attackEntityに `if(isAdd)` 前の処理を書き、別メソッド（例えば、attackEntityAddKnockback())に `entity,velocity.add(vector)` を書くことをおススメします。

2022-10-17 14:27 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
> +        userInventory = UserInventory(this)
初期に設定するスキルがあるとき、プレイヤーインベントリの初期化はスキルを設定した後でなければならないので、タイミングをずらしました。

2022-10-18 03:26 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
> +        userInventory = UserInventory(this)
初期に設定するスキルは、どのようなコードで設定するのですか。
もしinitブロック内で処理しない場合、移動する意味がないように思えます。

2022-10-18 04:34 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
> +        userInventory = UserInventory(this)
スキル構成の初期化はinitブロック内で行われます

2022-10-18 04:35 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
> +                entity.velocity = vector
コンフリクト回避のためここは別ブランチで実装します。

2022-10-18 04:45 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
> +    private fun attackEntity(entity: Entity, damage: Double, vector: Vector, isAdd: Boolean) {
別ブランチで実装します

2022-10-18 07:43 UTC, closed without merging