[結合]: 結合作業と簡単なバグを修正
eryuLab/SkillMaster pull request #220
Opened 2022-11-01 15:14 UTC by Koryu25

### 具体的な実装方法または変更点
- モードシステムの書き方を変更
- スキル「空の構え」のバグ修正
- スキルに標準の発動条件を実装
issue書かなくてごめんなさい

### 補足事項
補足事項を記載

### 関連するIssue
なし

2022-11-02 00:37 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/KaraNoKamae.kt
> +        user.player.velocity.add(vector)
```kotlin
user.damageAddVector(cut, vector)
```
では動かなかった感じですか？

2022-11-02 15:08 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/KaraNoKamae.kt
> +        user.player.velocity.add(vector)
ダメージ処理→防御→ダメージ処理→防御と、無限ループが発生したのでダメージを直接与えることにしました。

2022-11-02 15:09 UTC, Koryu25 commented
user.damage()の引数にnoDefense: Booleanを加えて、防御無視の機能を実装することで、問題を回避しました。

2022-11-03 10:04 UTC, hirotask approved these changes
![](https://camo.githubusercontent.com/898bb49d4b481a5aac47cb96544cc1bc43e08ffcfe11fc6743e84e7984fbcda4/68747470733a2f2f696d6167652e6c67746d6f6f6e2e6465762f313836303539)

2022-11-03 10:06 UTC, hirotask requested changes

2022-11-03 10:06 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
> +            player.velocity.add(vector)
damageChangeVectorメソッド内で、vectorをaddしているっぽい？

2022-11-03 14:37 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
> +            player.velocity.add(vector)
ミスです。直します

2022-11-04 05:25 UTC, hirotask approved these changes

2022-11-04 05:25 UTC, merged

2022-11-04 05:26 UTC, hirotask commented
凝集度が低くなるコードを書いてますが、それは別Issueで対応します