[品質向上]: モードクラスの実装
eryuLab/SkillMaster pull request #222
Opened 2022-11-02 02:10 UTC by Koryu25

### 具体的な実装方法または変更点
- ModeManagerにモードプロパティとモード変更時の処理を持たせた
- ユーザーにmodeプロパティを持たせた

### 補足事項
N/A

### 関連するIssue
- close #116

2022-11-02 02:49 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/user/ModeManager.kt
> +    fun shift(mode: UserMode) {
変数名に関して、modeとthis.modeよりもfromとtoとかにしたほうがわかりやすいと思います。

2022-11-02 15:09 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/user/ModeManager.kt
> +    fun shift(mode: UserMode) {
変えます。

2022-11-03 10:08 UTC, hirotask requested changes

2022-11-03 10:08 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/user/ModeManager.kt
> +class ModeManager(val user: SkillUser, var from: UserMode = UserMode.BATTLE) {
クラスのプロパティのUserModeまでfromという名前にしてしまうと分かりずらいので、shiftメソッド内のUserModeのみfromのほうがいいと思います。

2022-11-03 10:08 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/user/ModeManager.kt
> +class ModeManager(val user: SkillUser, var from: UserMode = UserMode.BATTLE) {
指定した位置分かりづらかったですね。すみません。

2022-11-04 05:27 UTC, hirotask approved these changes

2022-11-04 05:28 UTC, merged