[バグ]: スキルセット番号が変わらない
eryuLab/SkillMaster pull request #225
Opened 2022-11-03 07:26 UTC by Koryu25

### 具体的な実装方法または変更点
コードに汎用性がなかったため一から考え直した。  
条件分岐を繰り返した。

### 補足事項
N/A

### 関連するIssue
- close #224

2022-11-03 10:11 UTC, hirotask requested changes

2022-11-03 10:11 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/user/skillset/SkillCard.kt
>              }
変数iが使用されていないのですが、これは正しいコードですか？

2022-11-03 15:25 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/user/skillset/SkillCard.kt
>              }
正しいコードです

2022-11-04 05:49 UTC, hirotask requested changes

2022-11-04 05:49 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/user/skillset/SkillCard.kt
>              }
使用しない変数は`_`としておくケースが多いので、変更お願いします

2022-11-04 07:15 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/user/skillset/SkillCard.kt
>              }
了解しました

2022-11-04 09:09 UTC, Koryu25 commented
このように表示されて名前が変更できません。  
どのようにしたらいいですか
![image](https://user-images.githubusercontent.com/64457552/199935339-a186b6b3-4ba0-4dc4-a17a-cd26ae9c8417.png)

2022-11-04 09:43 UTC, hirotask commented
kotlinで`_`使えないの初めて知りましたすみません…（なんか[独自の文法](https://itneko.com/kotlin-underscore/)あるっぽいです）
そして、`_`の代わりにrepeat式っていうのが使えるっぽいので、それ使いましょう。
https://tokitsubaki.com/kotlin-for-while/736/#toc12

2022-11-04 10:37 UTC, hirotask approved these changes

2022-11-04 10:37 UTC, merged