[新機能]: アイテムでスキルのインターバルを表示
eryuLab/SkillMaster pull request #233
Opened 2022-11-06 09:07 UTC by Koryu25

### 具体的な実装方法または変更点
アイテムの使用クールダウンの機能を使ってスキルのインターバルを表示した。

### 補足事項
N/A

### 関連するIssue
- close #221

2022-11-08 09:51 UTC, hirotask requested changes

2022-11-08 09:51 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/skill/CompositeSkill.kt
> +        user.sendActionBar("" + ChatColor.RED + "複合スキル『" + name + "』終了")
`user.sendActionBar("${ChatColor.RED}複合スキル『$name』終了")` としたほうがいいと思います

2022-11-09 13:35 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/skill/CompositeSkill.kt
> +        user.sendActionBar("${ChatColor.RED}『" + name + "』終了")
これ`name`は+で結合している意図はなんですか？

2022-11-09 13:54 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/skill/CompositeSkill.kt
> +        user.sendActionBar("${ChatColor.RED}『" + name + "』終了")
わすれてました。なおします

2022-11-09 13:55 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/skill/CompositeSkill.kt
> +        user.sendActionBar("${ChatColor.RED}『" + name + "』終了")
もし「『』の中に空白があったほうが見やすい」とこりゅーさんが思ってつけたのであれば、実際にプレイする人も空白があったほうが見やすいと思うので、
```kotlin
user.sendActionBar("${ChatColor.RED}『  $name  』終了")
```
としたほうがいいと思います

2022-11-09 14:01 UTC, hirotask approved these changes
![](https://camo.githubusercontent.com/898bb49d4b481a5aac47cb96544cc1bc43e08ffcfe11fc6743e84e7984fbcda4/68747470733a2f2f696d6167652e6c67746d6f6f6e2e6465762f313836303539)

2022-11-09 14:01 UTC, merged