[バグ修正]: スラップステップのバグを修正
eryuLab/SkillMaster pull request #235
Opened 2022-11-07 12:17 UTC by Koryu25

### 具体的な実装方法または変更点
下方向にブロックがあるか判定するメソッドcheckBottom()を修正  

### 補足事項
N/A

### 関連するIssue
- close #234

2022-11-08 09:57 UTC, hirotask requested changes

2022-11-08 09:57 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/SlapStep.kt
>      }
BlockFaceを使った判定方法のほうがよりシンプルに書ける気がします。
例）
```kotlin
private fun checkBottom(): Boolean = user.player.location.block.getRelative(BlockFace.DOWN).type != Material.AIR
```

2022-11-09 09:35 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/SlapStep.kt
>      }
案の意図が理解できません。  
もう少し詳しくお願いします。  
ちなみにcheckBottom()は下の2ブロックのマテリアルを確認するコードです。  
blockFaceでは判定出来ないと思います。

2022-11-09 09:40 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/SlapStep.kt
>      }
下に２ブロックなければスラップステップは発動できないですね。なるほど。勘違いしてました。

2022-11-09 09:45 UTC, hirotask commented
あともう一つ改善できるポイントがあったので追記しておきます
```kotlin
 if (type1 == Material.AIR && type2 == Material.AIR)
            return false
return true
```
ですが、
```kotlin
return type1 != Material.AIR || type2  != Material.AIR
```
としたほうがいいと思います。

2022-11-09 13:34 UTC, Koryu25 commented
わかりにくいので直したくないです。

2022-11-09 13:42 UTC, hirotask commented
一応、参考までにプログラミングにおいては[サイクロマティック複雑度](https://qiita.com/uhooi/items/c77a53a4c7ac232a1ba1#:~:text=%E3%80%8C%E3%82%B5%E3%82%A4%E3%82%AF%E3%83%AD%E3%83%9E%E3%83%86%E3%82%A3%E3%83%83%E3%82%AF%E8%A4%87%E9%9B%91%E5%BA%A6%20%28Cyclomatic%20complexity%29%E3%80%8D%E3%81%A8%E3%81%AF%E3%80%81McCabe%E3%81%AB%E3%82%88%E3%81%A3%E3%81%A6%E6%8F%90%E5%94%B1%E3%81%95%E3%82%8C%E3%81%9F%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%81%AE%E8%A4%87%E9%9B%91%E3%81%95%E3%82%92%E7%A4%BA%E3%81%99%E6%8C%87%E6%A8%99%E3%81%A7%E3%81%99%E3%80%82,%E3%80%8C%E3%82%B5%E3%82%A4%E3%82%AF%E3%83%AD%E3%83%9E%E3%83%81%E3%83%83%E3%82%AF%E6%95%B0%E3%80%8D%E3%82%84%E3%80%8C%E5%BE%AA%E7%92%B0%E7%9A%84%E8%A4%87%E9%9B%91%E5%BA%A6%E3%80%8D%E3%81%AA%E3%81%A9%E3%81%A8%E3%82%82%E5%91%BC%E3%81%B0%E3%82%8C%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%80%82%20%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E5%8D%98%E4%BD%8D%E3%81%A7%E8%A8%88%E6%B8%AC%E3%81%97%E3%80%81%E9%AB%98%E3%81%84%E3%81%BB%E3%81%A9%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%81%8C%E8%A4%87%E9%9B%91%E3%81%A8%E3%81%84%E3%81%86%E3%81%93%E3%81%A8%E3%82%92%E7%A4%BA%E3%81%97%E3%81%BE%E3%81%99%E3%80%82%20%E7%B0%A1%E5%8D%98%E3%81%AB%E3%81%84%E3%81%88%E3%81%B0%E3%80%81if%E3%82%84for%2C%20switch%E3%81%AA%E3%81%A9%E3%81%AE%E5%88%86%E5%B2%90%E3%81%8C%E5%A4%9A%E3%81%84%E3%81%BB%E3%81%A9%E5%80%A4%E3%81%8C%E9%AB%98%E3%81%8F%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82) というプログラムの複雑さの指標があり、その複雑さは
> の関数に含まれるIf/else・for・switch/case・while文の数によって計測

されます。したがって、if分やfor文が少なく順次処理を行うプログラムのほうが複雑度が低いです。
なので一般的にはif文を用いない
```kotlin
return type1 != Material.AIR || type2  != Material.AIR
```
のほうが「複雑度が低いプログラム」とされていることは念頭に入れておいてほしいです。

2022-11-09 13:52 UTC, hirotask commented
まあでも、これはこりゅーさん主体のシステムですのでマージします。

2022-11-09 13:53 UTC, merged