[update]:　２体のエンティティが立っている位置をつないだベクトルの角度を求めるメソッドの追加
eryuLab/SkillMaster pull request #237
Opened 2022-11-09 15:28 UTC by hirotask

### 具体的な実装方法または変更点
[プレイヤー間の角度の求め方.pdf](https://github.com/eryuLab/SkillMaster/files/9972465/default.pdf)

### 補足事項
N / A

### 関連するIssue
- close #236

2022-11-10 00:41 UTC, Koryu25 requested changes

2022-11-10 00:41 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/utils/TargetSearch.kt
> +            entities = entity.world.getNearbyEntities(entity.location, range, range, range)
entity.getNearByEntities()としないのはなぜですか？

2022-11-10 08:16 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/utils/TargetSearch.kt
> +            entities = entity.world.getNearbyEntities(entity.location, range, range, range)
公式ドキュメントによると、World#getNearbyEntities()とEntity#getNearbyEntities()には明確な違いがあり、
World#getNerbyEntities()は
> Returns a list of entities within a bounding box centered around a Location.
This may not consider entities in currently unloaded chunks. Some implementations may impose artificial restrictions on the size of the search bounding box. ([ここ](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#getNearbyEntities(org.bukkit.Location,double,double,double))より引用)

> Locationを中心としたバウンディングボックス内のエンティティのリストを返します。
これは、現在ロードされていないチャンク内のエンティティを考慮しない場合があります。実装によっては、検索境界ボックスのサイズに人工的な制限を課すことがあります。

であり、Entity#getNearbyEntities()は
>Returns a list of entities within a bounding box centered around this entity ([ここ](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html#getNearbyEntities(double,double,double))より引用)

> このエンティティを中心としたバウンディングボックスに含まれるエンティティのリストを返す

と書かれています。今回の実装の場合「実際に表示されているエンティティ」を対象としたほうが良いと思ったので
```kotlin
entities = entity.world.getNearbyEntities(entity.location, range, range, range)
```
としています。

2022-11-10 09:25 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/utils/TargetSearch.kt
> +            entities = entity.world.getNearbyEntities(entity.location, range, range, range)
でも
```kotlin
entity.world.getNearbyEntities(entity.location, range, range, range)
```
は冗長で
>This may not consider entities in currently unloaded chunks.

の部分がメソッド名に含まれていないので、Extensionで定義しなおす等したほうがAPI的には良いとは思います（）

2022-11-11 10:02 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/utils/TargetSearch.kt
> +        return Pair(theta, phi)
Pairという方はキーと値を持つクラスで合ってますか？  
その場合、なぜΘがキーでφが値なんですか？

2022-11-11 11:25 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/utils/TargetSearch.kt
> +        return Pair(theta, phi)
Pairは二つの値を返すクラスですね。調べたら解決しました。
OKです。マージします。

2022-11-11 11:25 UTC, merged