[update]:　新たなコマンドシステムの提案
eryuLab/SkillMaster pull request #241
Opened 2022-11-12 05:53 UTC by hirotask

### 具体的な実装方法または変更点
この提案によって改善される点
- コードのインデントが浅くなった
- SubCommandがわかりやすくなった

### 補足事項
補足事項を記載

### 関連するIssue
- close #Issue番号

2022-11-12 12:16 UTC, Koryu25 reviewed
構造は見やすくていいと思います。テストプレイはしまいしたか？

2022-11-12 12:52 UTC, Koryu25 requested changes

2022-11-12 12:52 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/SkillCommand.kt
> +                player.sendMessage("メニュー棒を付与しました")
メニュー棒を取得するコマンドが機能していません。  
/skill menu と入力してもコマンド構文エラーになります。

2022-11-12 14:27 UTC, hirotask commented
修正しましたが、この書き方の特性上少し冗長になってしまった気がします

2022-11-14 00:36 UTC, Koryu25 commented
テストプレイはしましたか？

2022-11-14 11:35 UTC, Koryu25 approved these changes
テストプレイしました。問題ありませんでした。マージします。

2022-11-14 11:35 UTC, merged