[新スキル]: 直剣「」
eryuLab/SkillMaster pull request #247
Opened 2022-11-15 04:15 UTC by Koryu25

### 具体的な実装方法または変更点
具体的な実装方法または変更点を記載

### 補足事項
補足事項を記載

### 関連するIssue
- close #Issue番号

2022-11-15 04:20 UTC, hirotask commented
@Koryu25 Conflictの解消お願いします

2022-11-15 07:40 UTC, Koryu25 commented
@hirotask コンフリクトなおしました。

2022-11-15 10:21 UTC, hirotask requested changes

2022-11-15 10:21 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/utils/TargetSearch.kt
> +     * @return 探索範囲内にlocがあるときtrueを返します
以下の点からコメントが分かりづらいです。
- 探索範囲内とはどこか
- locがないとき何を返すか処理を見ないとわからない

`正面の位置に引数に指定した地点locがあるか否かを返す`
のほうが分かりやすいと思います。

2022-11-17 13:22 UTC, hirotask approved these changes

2022-11-17 13:23 UTC, hirotask commented
コードは問題ありません
Conflictの解消をしてマージお願いします

2022-11-18 03:14 UTC, merged