[新機能]: スキルセットを保存するシステムを作成
eryuLab/SkillMaster pull request #259
Opened 2022-12-04 06:19 UTC by Koryu25

### 具体的な実装方法または変更点
ymlファイルにスキルセットを保存してリログしてもスキル構成が保持される機能を作った

### 補足事項
N/A

### 関連するIssue
- close #256

2022-12-05 12:19 UTC, hirotask requested changes

2022-12-05 12:19 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
> +    val skillSetList: List<SkillSet> = arrayListOf(
arrayListということは「SkillSetの数は5つよりも増えることがある」という仕様で間違いないですか？

2022-12-05 12:19 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
>      fun settable(skill: Skill): Boolean {
「V(動詞)できるかどうか」をあらわすときは ~able ではなく、「can + V(動詞)」とした名前のほうが分かりやすいと思います。
ここはコーディング規約にかかわってくるところなので、厳密に定めるかどうかあとで話し合いたいですね。

2022-12-07 07:43 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
> +    val skillSetList: List<SkillSet> = arrayListOf(
`増えることがある`　というのは、実際に
```kotlin
skillSetList.add(SkillSet(うんたら))
```
みたいな処理が現在考えている仕様の中で存在するか？という意味です

2022-12-07 14:58 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
>      fun settable(skill: Skill): Boolean {
こだわりとかないので直しておきます。
あとで話し合いましょう

2022-12-09 12:08 UTC, hirotask approved these changes
![LGTM](https://images.lgtmgen.org/67824c9c-a474-4dc7-874c-01323d3b2ac6)

2022-12-09 13:22 UTC, merged