Koryu25/game startup system second
eryuLab/SkillMaster pull request #282
Opened 2023-01-02 11:58 UTC by Koryu25

### 具体的な実装方法または変更点
- 待機部屋につながるゲートを追加
- 人数集めとゲーム開始までを担当するルーム(待機部屋)を追加
- ゲーム終了時にロビーへTPするように変更

### テストして頂きたいこと
テストの方法やコマンドは下に書いてます。
- [ ]  ゲートを作成できるか
- [ ] ゲートの中央にゲートの名前の書いてあるホログラムが映るか
- [ ] ゲートを削除できるか
- [ ] ルームを作成できるか
- [ ] ルームを削除できるか
- [ ] ゲートからルームにアクセスできるか
- [ ] ルームのホログラムにルーム名、ゲームタイプ、状態、必要人数、現在の人数、開始までのカウントダウンが表示されるか
- [ ] ルームからゲームが開始できるか
- [ ] ゲートとルームが鯖を再起しても情報が保持されているか

### 操作方法とコマンド
#### ゲートの作成方法
WorldEditの斧で二点を選択し、ゲートの範囲を決める  
以下のコマンドを入力する  
/skill gate create [gate-name] [game-type]  

#### ゲートの削除方法
以下のコマンドを入力する
/skill gate delete [gate-name]

#### ルームの作成方法(2つのコマンド)
以下のコマンドを入力するのですが、、、  
以下のコマンドを入力するとき、コマンド送信者が立っている位置がルームにアクセスするときのテレポート座標になる(ゲートをくぐったらコマンド送信者の立っている位置にTPされる)  
/skill room create [room-name] [game-type]  
※まだルームは作成されていません。  
以下のコマンドを入力します  
こちらはコマンド送信者の座標がホログラムの座標となります。  
/skill room hologram  
これでルームの作成は完了です。  

#### ルームの削除方法
以下のコマンドを入力します。  
/skill room delete [room-name]

### 補足事項
- ゲートとルームにはゲームタイプが設定されていて、DuelモードのゲートはDuelモードのルームにしか接続されません。
- ルーム内やゲーム中のプレイヤーはゲートにアクセスできません。

### 関連するIssue
- close #269

2023-01-02 13:53 UTC, hirotask requested changes
テストは今できない状況なのであとでやります

2023-01-02 13:53 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/gate/GateList.kt
> +    fun duplicateName(name: String): Boolean {
Boolean型を返すのであれば、メソッド名を`isDuplicatedName`としたほうがわかりやすいと思います。

2023-01-02 13:53 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/room/GameRoom.kt
> +        hologram.appendTextLine("[ Now: ${playerList.size} ]")
保守性の観点から、一度ホログラムに設定するメッセージをArrayにしてからそれをfor文でループさせて設定するほうがいいと思います。
こんな感じ↓
```
val waitingHologram = arrayOf("[ $name ]", "[ ${gameType.en} waiting... ]", "[ Required: ${gameType.numberOfPlayer} ]", "[ Now: ${playerList.size} ]")
for (text in waitingHologram) {
    hologram.appendTextLine(text)
}
```

2023-01-02 13:53 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/room/GameRoom.kt
> +            hologram.appendTextLine("[ Start in: $count ]")
上のレビューに同じ

2023-01-02 13:53 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/room/GameRoom.kt
> +    }
変数`firstInvoke`で処理を分けているのは、凝集度の観点から別メソッドにしたほうがいいと思います。
例えば、`updateFirstStartingHologram`と`updateStartingHologram`みたいな感じで

2023-01-02 13:53 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/room/GameRoom.kt
> +            }
【質問】
Kotlinにはsmart cast機能があったはずなので、when式を使用している場合`as`を用いた明示的キャストをしなくてもOKなような気がしたのですが、smart castは動かなかった感じですか？

2023-01-02 13:53 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/room/RoomCreator.kt
> +        fun has(player: Player): Boolean {
`hasPlayer`としっかりと書いたほうがわかりやすいと思います

2023-01-02 13:53 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/room/RoomCreator.kt
> +        private val LIST = RoomCreatorList()
companion objectで定数を定義する場合は`const`を使用したほうがいいと思います（[理由](https://qiita.com/takusemba/items/f278e9e9e9217f0d6632)）
あと、確認なんですが`LIST`を呼び出し時ではなく、`RoomCreator`クラスの初期化時(インスタンス生成時）に初期化したかったからcompanion objectを使ったという認識であっていますか？

2023-01-02 13:53 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/room/RoomList.kt
> +    val set: MutableSet<GameRoom> = mutableSetOf()
命名を`loadRoomSet`としたほうが良いと思います

2023-01-03 00:03 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/gate/GateList.kt
> +    fun duplicateName(name: String): Boolean {
isにしちゃうとGateList自体が重複してるみたいなので、hasGateNamed(name: String)に変えようと思います。

2023-01-03 00:04 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/room/GameRoom.kt
> +        hologram.appendTextLine("[ Now: ${playerList.size} ]")
たしかに！やります

2023-01-03 00:08 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/room/GameRoom.kt
> +    }
直します

2023-01-03 00:21 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/room/GameRoom.kt
> +            }
動きませんでした。  
プロパティの"game"は定数でなく変数なので、キャストを行う時点で型が変わっている可能性があるそうです。  
<img width="646" alt="image" src="https://user-images.githubusercontent.com/64457552/210286700-98767380-1b28-4bf9-8b70-f6537faf84c5.png">

2023-01-03 00:21 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/room/RoomCreator.kt
> +        fun has(player: Player): Boolean {
直します

2023-01-03 00:27 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/room/RoomCreator.kt
> +        private val LIST = RoomCreatorList()
シングルトンとして使いたかったからです。

2023-01-03 00:29 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/room/RoomList.kt
> +    val set: MutableSet<GameRoom> = mutableSetOf()
どちらのプロパティのことですか？

2023-01-03 00:35 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/room/RoomCreator.kt
> +        private val LIST = RoomCreatorList()
constつけます

2023-01-03 00:36 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/room/RoomCreator.kt
> +        private val LIST = RoomCreatorList()
あ、これプリミティブじゃないからつけれなかった

2023-01-03 00:37 UTC, Koryu25 commented
@hirotask レビュー一通り確認しました。

2023-01-07 15:51 UTC, hirotask commented
@Koryu25 残りのタスクは一人ではできないので、後日テストプレイしましょう

2023-01-12 14:51 UTC, hirotask approved these changes
![LGTM](https://images.lgtmgen.org/8f789937-7fa9-4dff-98a5-af24551674fa)

2023-01-13 11:51 UTC, merged